name: universal_date_parser
description: A highly optimized, auto-detecting date parser for Dart/Flutter. Supports ISO, slash, dash, dot, text, US, RFC, and compact formats.
version: 1.1.0
repository: https://github.com/pragneshkoli/universal_date_parser
issue_tracker: https://github.com/pragneshkoli/universal_date_parser/issues


environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
